[package]
name = "raytrace"
version = "0.1.0"
edition = "2024"

[lib]
name = "raytrace"

[dependencies]
indicatif = { version = "0.17.11", features = ["rayon"] }
itertools = "0.14.0"
lerp = "0.5.0"
nalgebra = "0.33.2"
rand = "0.9.1"
approx = "0.5.1"
rayon = "1.10.0"
